import type { EventWithGroup, Group, Event } from "@shared/schema";

/**
 * 岡山県内3大学のサークル・部活動情報レポートに基づいたサンプルデータ
 * 参考: 岡山県内3大学のサークル・部活動情報レポート (2025年版)
 */

export const sampleGroups: Group[] = [
  // 岡山大学 (11団体)
  {
    id: "okadai-kyudo",
    name: "体育会弓道部",
    university: "岡山大学",
    category: "部活",
    genre: "弓道",
    description: "弓道の稽古、大会出場。初心者も歓迎しており、2026年3月には新歓説明会を実施するなど、活発な新人勧誘を行っています。真剣に競技に取り組む一方で、新生への手厚いサポートもあり、アットホームな雰囲気です。",
    atmosphereTags: ["初心者歓迎", "アットホーム", "真剣"],
    beginnerFriendly: true,
    instagramUrl: "https://instagram.com/okadai__kyudo",
    createdAt: new Date(),
  },
  {
    id: "okadai-football",
    name: "アメリカンフットボール部 (BADGERS)",
    university: "岡山大学",
    category: "部活",
    genre: "アメリカンフットボール",
    description: "アメリカンフットボールの練習および試合。2026年3月6日には新歓PVを公開し、新入生へのアピールを積極的に行っています。チームワークを重視し、目標に向かって努力する熱い雰囲気です。",
    atmosphereTags: ["チームワーク", "初心者歓迎", "熱い"],
    beginnerFriendly: true,
    instagramUrl: "https://instagram.com/ouafc_shinkan",
    createdAt: new Date(),
  },
  {
    id: "okadai-badminton",
    name: "医歯薬バドミントン部",
    university: "岡山大学",
    category: "部活",
    genre: "バドミントン",
    description: "医・歯・薬・看護の全学部合同でバドミントン活動を行っています。部員規模75名と大規模で、2026年3月には新歓情報を更新し、4月からの新歓活動を予定しています。学部を超えた交流があり、初心者から経験者まで幅広く楽しめる環境です。",
    atmosphereTags: ["初心者歓迎", "交流", "大規模"],
    beginnerFriendly: true,
    memberCount: 75,
    instagramUrl: "https://instagram.com/okadai_ishiyaku_badminton",
    createdAt: new Date(),
  },
  {
    id: "okadai-music",
    name: "軽音サークル「音楽室」",
    university: "岡山大学",
    category: "サークル",
    genre: "音楽",
    description: "軽音楽の演奏活動、ライブイベントの企画・実施。2026年3月には新歓アカウントを始動し、新入生向けの情報を発信しています。音楽好きが集まり、自由に表現できるクリエイティブな雰囲気です。",
    atmosphereTags: ["創造的", "初心者歓迎", "自由"],
    beginnerFriendly: true,
    twitterUrl: "https://twitter.com/musicroom2026",
    createdAt: new Date(),
  },
  {
    id: "okadai-photo",
    name: "写真部",
    university: "岡山大学",
    category: "サークル",
    genre: "写真",
    description: "写真撮影、作品制作、展示会開催。2025年10月にはラジオ出演、夏展2025を開催するなど、学内外で積極的に活動しています。創作意欲の高い部員が多く、写真を通じて自己表現を楽しむことができます。",
    atmosphereTags: ["創造的", "自由", "アットホーム"],
    beginnerFriendly: true,
    createdAt: new Date(),
  },
  {
    id: "okadai-art",
    name: "美術部",
    university: "岡山大学",
    category: "サークル",
    genre: "美術",
    description: "絵画、彫刻、デザインなど様々な美術活動。X（旧Twitter）にて部展情報や活動の様子を継続的に発信しています。自由に創作活動ができる環境で、部員同士の交流も盛んです。",
    atmosphereTags: ["創造的", "自由", "交流"],
    beginnerFriendly: true,
    twitterUrl: "https://twitter.com/okadaiart",
    createdAt: new Date(),
  },
  {
    id: "okadai-ds",
    name: "DS部 (データサイエンス)",
    university: "岡山大学",
    category: "サークル",
    genre: "データサイエンス",
    description: "データサイエンスとアイデアを使い、身近な問題を解決したり、自身のやりたいことを実現したりするサークルです。教授や企業と連携したプロジェクトも実施しており、2025年も継続して活動しています。知的好奇心旺盛な学生が集まり、真剣に学術的な探求を行う雰囲気です。",
    atmosphereTags: ["学術的", "実践的", "真剣"],
    beginnerFriendly: true,
    instagramUrl: "https://instagram.com/okadai_dsc",
    createdAt: new Date(),
  },
  {
    id: "okadai-scop",
    name: "SCoP (まちづくり)",
    university: "岡山大学",
    category: "サークル",
    genre: "社会貢献",
    description: "岡山プロスポーツ文化まちづくりサークルとして、プロスポーツを通じたまちの活性化を目指しています。奉還町商店街を拠点に、プロスポーツと街を繋ぐイベントの企画運営を行い、2025年にはワークショップを開催しました。地域貢献への意識が高く、実践的な活動を通じて社会性を養うことができます。",
    atmosphereTags: ["社会貢献", "実践的", "地域密着"],
    beginnerFriendly: true,
    instagramUrl: "https://instagram.com/scop_okayama",
    createdAt: new Date(),
  },
  {
    id: "okadai-baton",
    name: "おかやまバトン (被災地支援)",
    university: "岡山大学",
    category: "サークル",
    genre: "ボランティア",
    description: "3.11をきっかけに設立された団体で、「息の長い被災地支援」と「災害に強い岡山作り」をコンセプトに活動しています。防災教育や募金活動、防災ボランティア活動を2025年も継続して実施しています。社会貢献への意識が高く、助け合いの精神を大切にする温かい雰囲気です。",
    atmosphereTags: ["社会貢献", "温かい", "実践的"],
    beginnerFriendly: true,
    instagramUrl: "https://instagram.com/okayama_baton",
    createdAt: new Date(),
  },
  {
    id: "okadai-track",
    name: "陸上競技部 (中・長距離)",
    university: "岡山大学",
    category: "部活",
    genre: "陸上競技",
    description: "陸上競技の中・長距離種目の練習、大会出場。2025年度の活動レポートをInstagramで公開しており、日々の練習の様子を積極的に発信しています。競技力向上を目指し、日々練習に励む真剣な雰囲気です。",
    atmosphereTags: ["真剣", "実践的", "競技力向上"],
    beginnerFriendly: false,
    instagramUrl: "https://instagram.com/okadai_tf_long",
    createdAt: new Date(),
  },
  {
    id: "okadai-shikada-kyudo",
    name: "鹿田弓道部",
    university: "岡山大学",
    category: "部活",
    genre: "弓道",
    description: "弓道の稽古、大会出場。鹿田キャンパスを拠点に活動しており、2026年3月には新歓イベントを実施しています。弓道を通じて精神を鍛え、礼儀作法を重んじる厳粛な雰囲気です。",
    atmosphereTags: ["真剣", "礼儀", "初心者歓迎"],
    beginnerFriendly: true,
    twitterUrl: "https://twitter.com/skt_kyd_shinkan",
    createdAt: new Date(),
  },

  // 岡山理科大学 (10団体)
  {
    id: "ous-edpken",
    name: "情報処理研究部 (EDPKEN)",
    university: "岡山理科大学",
    category: "部活",
    genre: "プログラミング",
    description: "1971年設立の伝統ある部活で、主にコンピュータを使用した活動（プログラミング、CG、DTM、電子工作など）を行っています。2026年も継続して活動しており、高い専門性を追求しています。技術探求に熱心な学生が多く、互いに知識を共有し高め合う雰囲気です。",
    atmosphereTags: ["技術的", "真剣", "学術的"],
    beginnerFriendly: true,
    instagramUrl: "https://instagram.com/edpken",
    contactInfo: "https://www.edp-ken.com/",
    createdAt: new Date(),
  },
  {
    id: "ous-science-solution",
    name: "科学部ソリューション班",
    university: "岡山理科大学",
    category: "サークル",
    genre: "科学",
    description: "科学を通じて様々な課題解決に取り組んでいます。部費は0円で、2025年末には紹介動画を公開するなど、活動内容を積極的に発信しています。自由な思想で科学の面白さを追求し、実践的な学びを重視する雰囲気です。",
    atmosphereTags: ["学術的", "実践的", "自由"],
    beginnerFriendly: true,
    createdAt: new Date(),
  },
  {
    id: "ous-kintore",
    name: "筋トレ愛好会",
    university: "岡山理科大学",
    category: "サークル",
    genre: "フィットネス",
    description: "主にフィットネスルームを利用し、筋力トレーニングを行っています。2025年には活動日変更の報告があり、継続して活動しています。健康志向が高く、自身の身体を鍛えることに熱心な学生が集まっています。",
    atmosphereTags: ["健康志向", "実践的", "初心者歓迎"],
    beginnerFriendly: true,
    instagramUrl: "https://instagram.com/ous_kintore",
    createdAt: new Date(),
  },
  {
    id: "ous-rac",
    name: "理大RAC (ローターアクトクラブ)",
    university: "岡山理科大学",
    category: "サークル",
    genre: "ボランティア",
    description: "約50名の部員が在籍し、地域と交流しながら清掃活動、子ども向け教室、イベント出店など多岐にわたるボランティア活動を行っています。2025年も活動に活躍しています。地域社会への貢献意識が高く、仲間との絆を大切にするアットホームな雰囲気です。",
    atmosphereTags: ["社会貢献", "地域密着", "アットホーム"],
    beginnerFriendly: true,
    memberCount: 50,
    instagramUrl: "https://instagram.com/oridai_rac",
    createdAt: new Date(),
  },
  {
    id: "ous-keiei-project",
    name: "経営学部 学生プロジェクト",
    university: "岡山理科大学",
    category: "サークル",
    genre: "ビジネス",
    description: "経営学部の学生が主体となり、様々なプロジェクトを企画・実行しています。2026年2月には1年間の活動発表会を実施し、その成果を報告しました。実践的な学びを重視し、ビジネスや社会課題解決に意欲的な学生が集まっています。",
    atmosphereTags: ["実践的", "学術的", "ビジネス"],
    beginnerFriendly: true,
    instagramUrl: "https://instagram.com/ous_keiei_project",
    createdAt: new Date(),
  },
  {
    id: "ous-kyudo",
    name: "弓道部",
    university: "岡山理科大学",
    category: "部活",
    genre: "弓道",
    description: "弓道の稽古と大会出場を主な活動としています。伝統を重んじ、集中力と精神力を高めることを目指す厳粛な雰囲気です。",
    atmosphereTags: ["真剣", "礼儀", "伝統"],
    beginnerFriendly: false,
    createdAt: new Date(),
  },
  {
    id: "ous-brass",
    name: "吹奏楽団",
    university: "岡山理科大学",
    category: "部活",
    genre: "音楽",
    description: "吹奏楽の練習、学内イベントでの演奏、定期演奏会の開催。2025年度も学内イベントと定期演奏会で活動しています。音楽を通じて仲間と協力し、美しいハーモニーを奏でることを楽しむ雰囲気です。",
    atmosphereTags: ["音楽", "協力", "初心者歓迎"],
    beginnerFriendly: true,
    createdAt: new Date(),
  },
  {
    id: "ous-esports",
    name: "e-Sports研究会",
    university: "岡山理科大学",
    category: "サークル",
    genre: "ゲーム",
    description: "e-Sportsに関する研究や実践。学友会HPにて2025年度も活動継続が確認されています。ゲーム好きが集まり、戦略や技術を追求する熱できる雰囲気です。",
    atmosphereTags: ["ゲーム", "実践的", "真剣"],
    beginnerFriendly: true,
    createdAt: new Date(),
  },
  {
    id: "ous-event",
    name: "とり.OUS (イベント企画)",
    university: "岡山理科大学",
    category: "サークル",
    genre: "イベント企画",
    description: "学内および学外でのイベント企画・運営。2025年度も学内イベントの企画・運営を実施しています。創造性豊かで、イベントを通じて人を楽しませることに情熱を燃やす学生が集まっています。",
    atmosphereTags: ["創造的", "イベント", "初心者歓迎"],
    beginnerFriendly: true,
    createdAt: new Date(),
  },
  {
    id: "ous-dance",
    name: "ダンス部 (Mod-kiD)",
    university: "岡山理科大学",
    category: "部活",
    genre: "ダンス",
    description: "ストリートダンスを中心に、様々なジャンルのダンス練習、発表。2025年度も大学祭や外部イベントでパフォーマンスを披露しています。ダンスを通じて自己表現を楽しみ、仲間と切磋琢磨するエネルギッシュな雰囲気です。",
    atmosphereTags: ["ダンス", "自己表現", "初心者歓迎"],
    beginnerFriendly: true,
    instagramUrl: "https://instagram.com/modkid.dance",
    createdAt: new Date(),
  },

  // ノートルダム清心女子大学 (10団体)
  {
    id: "ndsu-acappella",
    name: "アカペラサークル ビリペル",
    university: "ノートルダム清心女子大学",
    category: "サークル",
    genre: "音楽",
    description: "岡山大学との合同アカペラサークルで、J-pop、アニソン、洋楽など幅広いジャンルのアカペラを歌っています。100名以上の大規模サークルで、2026年も活発に活動しています。音楽を通じて仲間と深く交流し、ハーモニーを追求する楽しい雰囲気です。",
    atmosphereTags: ["音楽", "交流", "初心者歓迎"],
    beginnerFriendly: true,
    memberCount: 100,
    instagramUrl: "https://instagram.com/biripel__acappella",
    createdAt: new Date(),
  },
  {
    id: "ndsu-children",
    name: "児童文化部",
    university: "ノートルダム清心女子大学",
    category: "サークル",
    genre: "社会貢献",
    description: "子ども向けのイベント企画・実施。2025年11月の大学祭では子ども向けイベントを開催し、地域の子どもたちとの交流を深めています。子ども好きの学生が集まり、楽しい活動を通じて創造性と思いやりを育てる雰囲気です。",
    atmosphereTags: ["社会貢献", "子ども向け", "創造的"],
    beginnerFriendly: true,
    createdAt: new Date(),
  },
  {
    id: "ndsu-glanz",
    name: "ダンスサークル Glanz",
    university: "ノートルダム清心女子大学",
    category: "サークル",
    genre: "ダンス",
    description: "ノートルダム清心女子大学の学生のみで構成されるダンスサークル。学内イベントや地域のイベントでダンスを披露しており、2025年度も大学祭でオープンキャンパスで活動しています。華やかでエネルギッシュな雰囲気で、ダンスを通じて自己表現を楽しんでいます。",
    atmosphereTags: ["ダンス", "自己表現", "初心者歓迎"],
    beginnerFriendly: true,
    instagramUrl: "https://instagram.com/glanz_ndsu",
    createdAt: new Date(),
  },
  {
    id: "ndsu-gakusai",
    name: "大学祭実行委員会",
    university: "ノートルダム清心女子大学",
    category: "委員会",
    genre: "イベント企画",
    description: "大学祭の企画・運営。2025年度の第60回大学祭を成功裏に運営し、SNSでも活発に情報を発信しています。イベント成功に向けて、責任感と協調性を持って取り組む真剣な雰囲気です。",
    atmosphereTags: ["イベント", "協力", "責任感"],
    beginnerFriendly: true,
    instagramUrl: "https://instagram.com/ndsu.gakusai.2025",
    createdAt: new Date(),
  },
  {
    id: "ndsu-isa",
    name: "I.S.A. (国際学生協会)",
    university: "ノートルダム清心女子大学",
    category: "サークル",
    genre: "国際交流",
    description: "岡山大学との合同で国際交流活動を行っています。留学生との交流イベントや異文化理解を深める活動を2025年度も継続しています。グローバルな視点を持ち、多様な文化に触れることができる刺激的な雰囲気です。",
    atmosphereTags: ["国際交流", "多文化", "初心者歓迎"],
    beginnerFriendly: true,
    twitterUrl: "https://twitter.com/isaokayama2",
    createdAt: new Date(),
  },
  {
    id: "ndsu-shodo",
    name: "書道部",
    university: "ノートルダム清心女子大学",
    category: "サークル",
    genre: "書道",
    description: "書道の練習、作品制作、展示会開催。2025年度の大学祭では作品展やパフォーマンスを実施しています。書道を通じて集中力と精神力を高め、日本の伝統文化を継承する厳粛な雰囲気です。",
    atmosphereTags: ["伝統", "集中力", "初心者歓迎"],
    beginnerFriendly: true,
    createdAt: new Date(),
  },
  {
    id: "ndsu-chado",
    name: "茶道部",
    university: "ノートルダム清心女子大学",
    category: "サークル",
    genre: "茶道",
    description: "茶道の稽古、お茶会の開催。2025年度の大学祭ではお茶会を実施し、来場者をもてなしました。茶道を通じて礼儀作法を学び、和の心を大切にする落ち着いた雰囲気です。",
    atmosphereTags: ["伝統", "礼儀", "初心者歓迎"],
    beginnerFriendly: true,
    createdAt: new Date(),
  },
  {
    id: "ndsu-broadcast",
    name: "放送研究部",
    university: "ノートルダム清心女子大学",
    category: "サークル",
    genre: "放送",
    description: "学内放送の制作、イベントの音響運営、番組制作。2025年度の大学祭では音響運営や番組制作を担当しました。放送を通じて情報を発信し、イベントを盛り上げることに情熱を燃やすクリエイティブな雰囲気です。",
    atmosphereTags: ["創造的", "技術的", "初心者歓迎"],
    beginnerFriendly: true,
    createdAt: new Date(),
  },
  {
    id: "ndsu-ecolo",
    name: "環境部 ECOLO",
    university: "ノートルダム清心女子大学",
    category: "サークル",
    genre: "環境",
    description: "学内の環境美化活動、環境問題に関する啓発活動。2025年度も継続して活動しています。環境問題に関心が高く、持続可能な社会の実現に向けて行動する意識の高い学生が集まっています。",
    atmosphereTags: ["社会貢献", "環境", "実践的"],
    beginnerFriendly: true,
    createdAt: new Date(),
  },
  {
    id: "ndsu-shuwa",
    name: "手話クラブ",
    university: "ノートルダム清心女子大学",
    category: "サークル",
    genre: "手話",
    description: "手話の練習、手話を通じた交流活動。2025年度も手話の練習や交流会を実施しています。聴覚障がい者への理解を深め、手話を通じてコミュニケーションの輪を広げる温かい雰囲気です。",
    atmosphereTags: ["社会貢献", "交流", "初心者歓迎"],
    beginnerFriendly: true,
    createdAt: new Date(),
  },
];

export const sampleEvents: Event[] = [
  // 岡山大学の新歓イベント
  {
    id: "okadai-kyudo-shinkan",
    groupId: "okadai-kyudo",
    title: "体育会弓道部 新歓説明会",
    description: "弓道部の活動内容や雰囲気を知ることができる新歓説明会です。初心者向けの説明もあり、弓道に興味のある新入生を大歓迎します。",
    date: new Date("2026-03-15T14:00:00Z"),
    location: "岡山大学 津島キャンパス 体育館",
    beginnerWelcome: true,
    soloFriendliness: 4,
    atmosphereTags: ["新歓", "説明会", "初心者歓迎"],
    status: "approved",
    createdAt: new Date(),
  },
  {
    id: "okadai-football-shinkan",
    groupId: "okadai-football",
    title: "アメリカンフットボール部 新歓PV公開",
    description: "アメリカンフットボール部の活動を紹介するPVが公開されます。部の雰囲気や練習風景を動画で確認できます。",
    date: new Date("2026-03-06T00:00:00Z"),
    location: "オンライン",
    beginnerWelcome: true,
    soloFriendliness: 3,
    atmosphereTags: ["新歓", "動画", "初心者歓迎"],
    status: "approved",
    createdAt: new Date(),
  },
  {
    id: "okadai-badminton-shinkan",
    groupId: "okadai-badminton",
    title: "医歯薬バドミントン部 新歓イベント",
    description: "バドミントン部の新歓イベントです。初心者向けの基礎練習から経験者向けの試合まで、幅広いレベルで楽しめます。",
    date: new Date("2026-04-01T15:00:00Z"),
    location: "岡山大学 総合体育館",
    beginnerWelcome: true,
    soloFriendliness: 5,
    atmosphereTags: ["新歓", "体験", "初心者歓迎"],
    status: "approved",
    createdAt: new Date(),
  },

  // 岡山理科大学の新歓イベント
  {
    id: "ous-edpken-shinkan",
    groupId: "ous-edpken",
    title: "情報処理研究部 新歓説明会",
    description: "プログラミング、CG、DTMなど様々な技術活動を紹介する説明会です。初心者向けのプロジェクトもあり、技術に興味のある新入生を大歓迎します。",
    date: new Date("2026-03-20T16:00:00Z"),
    location: "岡山理科大学 情報系棟",
    beginnerWelcome: true,
    soloFriendliness: 4,
    atmosphereTags: ["新歓", "技術", "初心者歓迎"],
    status: "approved",
    createdAt: new Date(),
  },

  // ノートルダム清心女子大学の新歓イベント
  {
    id: "ndsu-acappella-shinkan",
    groupId: "ndsu-acappella",
    title: "アカペラサークル ビリペル 新歓ライブ",
    description: "アカペラの魅力を知ることができる新歓ライブです。先輩たちの演奏を聴いて、アカペラの楽しさを感じてみましょう。",
    date: new Date("2026-03-25T18:00:00Z"),
    location: "ノートルダム清心女子大学 講堂",
    beginnerWelcome: true,
    soloFriendliness: 4,
    atmosphereTags: ["新歓", "ライブ", "音楽"],
    status: "approved",
    createdAt: new Date(),
  },
  {
    id: "ndsu-children-shinkan",
    groupId: "ndsu-children",
    title: "児童文化部 新歓説明会",
    description: "子ども向けのイベント企画について学べる説明会です。子どもたちの笑顔を作ることに興味のある新入生を大歓迎します。",
    date: new Date("2026-03-22T15:00:00Z"),
    location: "ノートルダム清心女子大学 学生ホール",
    beginnerWelcome: true,
    soloFriendliness: 5,
    atmosphereTags: ["新歓", "説明会", "初心者歓迎"],
    status: "approved",
    createdAt: new Date(),
  },
];

// EventWithGroup型のデータを作成
export const eventsWithGroups: EventWithGroup[] = sampleEvents.map(event => {
  const group = sampleGroups.find(g => g.id === event.groupId)!;
  return {
    ...event,
    group,
  };
});

// GroupWithEvents型のデータを作成
export const groupsWithEvents = sampleGroups.map(group => ({
  ...group,
  events: sampleEvents.filter(e => e.groupId === group.id),
}));
